version: '3.1'
services:
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
            
    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - './db:/data/db'
        environment:
            - POSTGRES_USER=pg
            - POSTGRES_PASSWORD=pg
            - POSTGRES_DB=mash
        ports:
            - '5432:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'

    api:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
